// src/components/reports/ReportPDF.tsx

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";

// ─── Types ────────────────────────────────────────────────────────────────────

type ReportType = "patients" | "appointments" | "revenue" | "records";

interface ReportPDFParams {
  reportType: ReportType;
  data: Record<string, unknown>[];
  summary: Record<string, unknown>;
  fromDate?: string;
  toDate?: string;
  generatedBy?: string;
}

// ─── Colors ───────────────────────────────────────────────────────────────────

const C = {
  primary: [37, 99, 235] as [number, number, number],
  dark: [15, 23, 42] as [number, number, number],
  mid: [71, 85, 105] as [number, number, number],
  light: [148, 163, 184] as [number, number, number],
  muted: [226, 232, 240] as [number, number, number],
  bg: [248, 250, 252] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  success: [16, 185, 129] as [number, number, number],
  warning: [245, 158, 11] as [number, number, number],
  danger: [239, 68, 68] as [number, number, number],
  purple: [139, 92, 246] as [number, number, number],
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

function fillRect(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  color: [number, number, number],
) {
  doc.setFillColor(...color);
  doc.rect(x, y, w, h, "F");
}

function drawHeader(doc: jsPDF, title: string, subtitle: string, W: number) {
  // Banner
  fillRect(doc, 0, 0, W, 38, C.primary);
  doc.setFillColor(99, 102, 241); // indigo accent
  doc.triangle(W - 50, 0, W, 0, W, 38, "F");

  doc.setTextColor(...C.white);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("SPRMS", 14, 14);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(187, 210, 255);
  doc.text("Secure Patient Record Management System", 14, 21);
  doc.text("Ahmadu Bello University Teaching Hospital, Zaria", 14, 27);

  // Title on right
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...C.white);
  doc.text(title, W - 14, 16, { align: "right" });

  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(187, 210, 255);
  doc.text(subtitle, W - 14, 24, { align: "right" });
}

function drawFooter(doc: jsPDF, W: number, H: number, generatedBy: string) {
  fillRect(doc, 0, H - 16, W, 16, C.dark);
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...C.light);
  doc.text(
    `Generated by ${generatedBy} on ${format(new Date(), "MMMM d, yyyy 'at' HH:mm")} — SPRMS`,
    W / 2,
    H - 7,
    { align: "center" },
  );
}

// ─── Patient Report PDF ───────────────────────────────────────────────────────

function generatePatientReportPDF(params: ReportPDFParams) {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();

  drawHeader(doc, "PATIENT RECORDS REPORT", "Demographics & Registration", W);

  // Date range info
  let y = 46;
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...C.mid);
  const dateRange =
    params.fromDate && params.toDate
      ? `Period: ${format(new Date(params.fromDate), "MMM d, yyyy")} – ${format(new Date(params.toDate), "MMM d, yyyy")}`
      : params.fromDate
        ? `From: ${format(new Date(params.fromDate), "MMM d, yyyy")}`
        : params.toDate
          ? `Until: ${format(new Date(params.toDate), "MMM d, yyyy")}`
          : "Period: All time";
  doc.text(dateRange, 14, y);
  doc.text(`Total Records: ${params.summary.total}`, W - 14, y, {
    align: "right",
  });

  y += 8;

  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    head: [
      [
        "Patient No.",
        "Name",
        "Date of Birth",
        "Gender",
        "Blood Group",
        "Phone",
        "City",
        "Records",
        "Registered",
      ],
    ],
    body: params.data.map((r) => {
      const count = r._count as { medicalRecords: number } | undefined;
      return [
        String(r.patientNumber ?? "—"),
        `${r.firstName} ${r.lastName}`,
        r.dateOfBirth
          ? format(new Date(r.dateOfBirth as string), "MMM d, yyyy")
          : "—",
        String(r.gender ?? "—"),
        String(r.bloodGroup ?? "—").replace(/_/g, " "),
        String(r.phone ?? "—"),
        String(r.city ?? "—"),
        String(count?.medicalRecords ?? 0),
        r.createdAt
          ? format(new Date(r.createdAt as string), "MMM d, yyyy")
          : "—",
      ];
    }),
    headStyles: {
      fillColor: C.primary,
      textColor: C.white,
      fontSize: 8,
      fontStyle: "bold",
    },
    bodyStyles: { fontSize: 7.5, textColor: C.dark },
    alternateRowStyles: { fillColor: C.bg },
    tableLineColor: C.muted,
    tableLineWidth: 0.15,
  });

  drawFooter(doc, W, H, params.generatedBy ?? "Admin");
  doc.save(`SPRMS-Patient-Report-${format(new Date(), "yyyy-MM-dd")}.pdf`);
}

// ─── Appointment Report PDF ───────────────────────────────────────────────────

function generateAppointmentReportPDF(params: ReportPDFParams) {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();

  drawHeader(doc, "APPOINTMENT SUMMARY", "Booking & Status Report", W);

  let y = 46;
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...C.mid);
  doc.text(`Total: ${params.summary.total}`, 14, y);

  // Status summary inline
  const statusSummary =
    (params.summary.statusSummary as Array<{
      status: string;
      _count: { status: number };
    }>) ?? [];

  const statusText = statusSummary
    .map((s) => `${s.status.replace(/_/g, " ")}: ${s._count.status}`)
    .join("  |  ");

  if (statusText) {
    doc.text(statusText, W - 14, y, { align: "right" });
  }

  y += 8;

  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    head: [
      [
        "Patient",
        "Patient No.",
        "Doctor",
        "Date & Time",
        "Type",
        "Status",
        "Reason",
      ],
    ],
    body: params.data.map((r) => {
      const p = r.patient as
        | { firstName: string; lastName: string; patientNumber: string }
        | undefined;
      const d = r.doctor as
        | { staffProfile?: { firstName: string; lastName: string } | null }
        | undefined;
      return [
        p ? `${p.firstName} ${p.lastName}` : "—",
        p?.patientNumber ?? "—",
        d?.staffProfile
          ? `Dr. ${d.staffProfile.firstName} ${d.staffProfile.lastName}`
          : "—",
        r.scheduledAt
          ? format(new Date(r.scheduledAt as string), "MMM d, yyyy h:mm a")
          : "—",
        String(r.type ?? "—").replace(/_/g, " "),
        String(r.status ?? "—").replace(/_/g, " "),
        String(r.reason ?? "—"),
      ];
    }),
    headStyles: {
      fillColor: [16, 185, 129] as [number, number, number],
      textColor: C.white,
      fontSize: 8,
      fontStyle: "bold",
    },
    bodyStyles: { fontSize: 7.5, textColor: C.dark },
    alternateRowStyles: { fillColor: C.bg },
    tableLineColor: C.muted,
    tableLineWidth: 0.15,
  });

  drawFooter(doc, W, H, params.generatedBy ?? "Admin");
  doc.save(`SPRMS-Appointment-Report-${format(new Date(), "yyyy-MM-dd")}.pdf`);
}

// ─── Revenue Report PDF ───────────────────────────────────────────────────────

function generateRevenueReportPDF(params: ReportPDFParams) {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();

  drawHeader(doc, "REVENUE & BILLING REPORT", "Financial Summary", W);

  // Summary banner
  let y = 44;
  const rev = params.summary as {
    total: number;
    totalRevenue: number;
    paidRevenue: number;
    pendingRevenue: number;
    overdueRevenue: number;
  };

  fillRect(doc, 14, y, W - 28, 18, C.bg);
  doc.setDrawColor(...C.muted);
  doc.setLineWidth(0.2);
  doc.rect(14, y, W - 28, 18);

  const summaryItems = [
    { label: "Total Invoices", value: String(rev.total) },
    {
      label: "Total Billed",
      value: `₦${(rev.totalRevenue ?? 0).toLocaleString()}`,
    },
    {
      label: "Collected",
      value: `₦${(rev.paidRevenue ?? 0).toLocaleString()}`,
    },
    {
      label: "Outstanding",
      value: `₦${((rev.pendingRevenue ?? 0) + (rev.overdueRevenue ?? 0)).toLocaleString()}`,
    },
  ];

  const colW = (W - 28) / 4;
  summaryItems.forEach((item, i) => {
    const x = 14 + i * colW + colW / 2;
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...C.mid);
    doc.text(item.label, x, y + 6, { align: "center" });
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...C.dark);
    doc.text(item.value, x, y + 14, { align: "center" });
  });

  y += 24;

  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    head: [
      ["Invoice No.", "Patient", "Amount", "Status", "Date Created", "Paid At"],
    ],
    body: params.data.map((r) => {
      const p = r.patient as
        | { firstName: string; lastName: string }
        | undefined;
      return [
        String(r.invoiceNumber ?? "—"),
        p ? `${p.firstName} ${p.lastName}` : "—",
        `₦${((r.totalAmount as number) ?? 0).toLocaleString("en-NG", {
          minimumFractionDigits: 2,
        })}`,
        String(r.paymentStatus ?? "—"),
        r.createdAt
          ? format(new Date(r.createdAt as string), "MMM d, yyyy")
          : "—",
        r.paidAt ? format(new Date(r.paidAt as string), "MMM d, yyyy") : "—",
      ];
    }),
    headStyles: {
      fillColor: [139, 92, 246] as [number, number, number],
      textColor: C.white,
      fontSize: 8,
      fontStyle: "bold",
    },
    bodyStyles: { fontSize: 7.5, textColor: C.dark },
    alternateRowStyles: { fillColor: C.bg },
    tableLineColor: C.muted,
    tableLineWidth: 0.15,
  });

  drawFooter(doc, W, H, params.generatedBy ?? "Admin");
  doc.save(`SPRMS-Revenue-Report-${format(new Date(), "yyyy-MM-dd")}.pdf`);
}

// ─── Medical Records Report PDF ───────────────────────────────────────────────

function generateRecordsReportPDF(params: ReportPDFParams) {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();

  drawHeader(doc, "MEDICAL RECORDS REPORT", "Clinical Records Summary", W);

  let y = 46;
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...C.mid);
  doc.text(`Total Records: ${params.summary.total}`, 14, y);

  y += 8;

  autoTable(doc, {
    startY: y,
    margin: { left: 14, right: 14 },
    head: [
      [
        "Record No.",
        "Patient",
        "Type",
        "Title",
        "ICD Code",
        "Created By",
        "Date",
      ],
    ],
    body: params.data.map((r) => {
      const p = r.patient as
        | { firstName: string; lastName: string }
        | undefined;
      const cb = r.createdBy as
        | { staffProfile?: { firstName: string; lastName: string } | null }
        | undefined;
      return [
        String(r.recordNumber ?? "—"),
        p ? `${p.firstName} ${p.lastName}` : "—",
        String(r.recordType ?? "—").replace(/_/g, " "),
        String(r.title ?? "—"),
        String(r.icdCode ?? "—"),
        cb?.staffProfile
          ? `${cb.staffProfile.firstName} ${cb.staffProfile.lastName}`
          : "—",
        r.createdAt
          ? format(new Date(r.createdAt as string), "MMM d, yyyy")
          : "—",
      ];
    }),
    headStyles: {
      fillColor: [139, 92, 246] as [number, number, number],
      textColor: C.white,
      fontSize: 8,
      fontStyle: "bold",
    },
    bodyStyles: { fontSize: 7.5, textColor: C.dark },
    alternateRowStyles: { fillColor: C.bg },
    tableLineColor: C.muted,
    tableLineWidth: 0.15,
  });

  drawFooter(doc, W, H, params.generatedBy ?? "Admin");
  doc.save(
    `SPRMS-Medical-Records-Report-${format(new Date(), "yyyy-MM-dd")}.pdf`,
  );
}

// ─── Master Export Function ───────────────────────────────────────────────────

export function generateReportPDF(params: ReportPDFParams) {
  switch (params.reportType) {
    case "patients":
      return generatePatientReportPDF(params);
    case "appointments":
      return generateAppointmentReportPDF(params);
    case "revenue":
      return generateRevenueReportPDF(params);
    case "records":
      return generateRecordsReportPDF(params);
    default:
      return generatePatientReportPDF(params);
  }
}
